import { MigrationInterface, QueryRunner } from "typeorm";

export class RelacionServicioPromptAndServicioTipoAnalisis17558131163671755813117544 implements MigrationInterface {
    name = 'RelacionServicioPromptAndServicioTipoAnalisis17558131163671755813117544'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "claves_analisis" DROP CONSTRAINT "FK_claves_analisis_servicio"`);
        await queryRunner.query(`DROP INDEX "IDX_AUDIOS_TRANSCRITO" ON "audios"`);
        await queryRunner.query(`DROP INDEX "IDX_DATA_AUDIOS_COMPOSITE" ON "data_audios"`);
        await queryRunner.query(`DROP INDEX "IDX_CLIENTES_NAME" ON "clientes"`);
        await queryRunner.query(`DROP INDEX "IDX_SERVICIOS_NAME" ON "servicios"`);
        await queryRunner.query(`DROP INDEX "IDX_ANALISIS_COMPOSITE" ON "analisis"`);
        await queryRunner.query(`DROP INDEX "IDX_PARAMETROS_ANALISIS_COMPOSITE" ON "parametros_analisis"`);
        await queryRunner.query(`ALTER TABLE "claves_analisis" DROP COLUMN "servicioId"`);
        await queryRunner.query(`ALTER TABLE "prompts" ADD "servicio_id" int`);
        await queryRunner.query(`ALTER TABLE "tipo_analisis" ADD "servicio_id" int`);
        await queryRunner.query(`ALTER TABLE "claves_analisis" ADD "servicio_id" int`);
        await queryRunner.query(`ALTER TABLE "audios" DROP CONSTRAINT "FK_215af9f45b18ca75e45bf8eb0f1"`);
        await queryRunner.query(`ALTER TABLE "audios" ALTER COLUMN "transcrito" int`);
        await queryRunner.query(`ALTER TABLE "audios" DROP CONSTRAINT "DF_2d75961dcfd770605ff40f6545d"`);
        await queryRunner.query(`ALTER TABLE "audios" ALTER COLUMN "servicio_id" int`);
        await queryRunner.query(`ALTER TABLE "data_audios" DROP CONSTRAINT "FK_3602b8cef079c15e5a6904bd845"`);
        await queryRunner.query(`ALTER TABLE "data_audios" ALTER COLUMN "valor" nvarchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "data_audios" ALTER COLUMN "audio_id" int`);
        await queryRunner.query(`ALTER TABLE "prompts" ALTER COLUMN "template" text`);
        await queryRunner.query(`ALTER TABLE "tipo_analisis" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "tipo_analisis" ADD "description" varchar(255)`);
        await queryRunner.query(`ALTER TABLE "clientes" ADD CONSTRAINT "UQ_0c14604e1a6e1b00fd341b1b2c0" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP CONSTRAINT "FK_2222734377bc9808ae98cf12ff1"`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD CONSTRAINT "UQ_7b530f4aec186b2f02dd7ec9d41" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "cliente_id" int`);
        await queryRunner.query(`ALTER TABLE "claves_audios" ALTER COLUMN "clave" nvarchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "claves_audios" ALTER COLUMN "descripcion" nvarchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analisis" DROP CONSTRAINT "FK_d1613a202455c30088f2e46f67d"`);
        await queryRunner.query(`ALTER TABLE "analisis" DROP CONSTRAINT "FK_65916bf2e092b02f14028789474"`);
        await queryRunner.query(`ALTER TABLE "analisis" ALTER COLUMN "transcripcion_id" int`);
        await queryRunner.query(`ALTER TABLE "analisis" ALTER COLUMN "parametro_id" int`);
        await queryRunner.query(`ALTER TABLE "parametros_analisis" DROP CONSTRAINT "FK_f3201dc908e496bd5bd7c02c154"`);
        await queryRunner.query(`ALTER TABLE "parametros_analisis" DROP CONSTRAINT "FK_02ed9f13fac5b9029187a67c015"`);
        await queryRunner.query(`ALTER TABLE "parametros_analisis" ALTER COLUMN "name" varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "parametros_analisis" ALTER COLUMN "prompt_id" int`);
        await queryRunner.query(`ALTER TABLE "parametros_analisis" ALTER COLUMN "tipo_analisis_id" int`);
        await queryRunner.query(`ALTER TABLE "data_analisis" DROP CONSTRAINT "FK_5ffef841f8f03bd6888d9404467"`);
        await queryRunner.query(`ALTER TABLE "data_analisis" DROP CONSTRAINT "FK_a976cce689ecc207b90becefff7"`);
        await queryRunner.query(`ALTER TABLE "data_analisis" ALTER COLUMN "analisis_id" int`);
        await queryRunner.query(`ALTER TABLE "data_analisis" ALTER COLUMN "clave_id" int`);
        await queryRunner.query(`ALTER TABLE "claves_analisis" DROP CONSTRAINT "UQ_2664718930326ce317d19ce0776"`);
        await queryRunner.query(`ALTER TABLE "claves_analisis" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "claves_analisis" ADD "descripcion" nvarchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transcripciones" DROP CONSTRAINT "FK_903a2d51d69ebfec640df10ae34"`);
        await queryRunner.query(`ALTER TABLE "transcripciones" DROP COLUMN "transcripcion"`);
        await queryRunner.query(`ALTER TABLE "transcripciones" ADD "transcripcion" nvarchar(255)`);
        await queryRunner.query(`ALTER TABLE "transcripciones" ALTER COLUMN "audio_id" int`);
        await queryRunner.query(`CREATE INDEX "IDX_e56c9150db8fb032219ce40ac5" ON "audios" ("file_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_4782c64a9308ca8fba2e787f9a" ON "transcripciones" ("file_name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "REL_903a2d51d69ebfec640df10ae3" ON "transcripciones" ("audio_id") WHERE "audio_id" IS NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audios" ADD CONSTRAINT "FK_215af9f45b18ca75e45bf8eb0f1" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_audios" ADD CONSTRAINT "FK_3602b8cef079c15e5a6904bd845" FOREIGN KEY ("audio_id") REFERENCES "audios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prompts" ADD CONSTRAINT "FK_086a37b64e93ca33df8effdf110" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipo_analisis" ADD CONSTRAINT "FK_027ab74c366428aabca2307d9b8" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD CONSTRAINT "FK_2222734377bc9808ae98cf12ff1" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "analisis" ADD CONSTRAINT "FK_d1613a202455c30088f2e46f67d" FOREIGN KEY ("transcripcion_id") REFERENCES "transcripciones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "analisis" ADD CONSTRAINT "FK_65916bf2e092b02f14028789474" FOREIGN KEY ("parametro_id") REFERENCES "parametros_analisis"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parametros_analisis" ADD CONSTRAINT "FK_f3201dc908e496bd5bd7c02c154" FOREIGN KEY ("prompt_id") REFERENCES "prompts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parametros_analisis" ADD CONSTRAINT "FK_02ed9f13fac5b9029187a67c015" FOREIGN KEY ("tipo_analisis_id") REFERENCES "tipo_analisis"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_analisis" ADD CONSTRAINT "FK_5ffef841f8f03bd6888d9404467" FOREIGN KEY ("analisis_id") REFERENCES "analisis"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_analisis" ADD CONSTRAINT "FK_a976cce689ecc207b90becefff7" FOREIGN KEY ("clave_id") REFERENCES "claves_analisis"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "claves_analisis" ADD CONSTRAINT "FK_07075d2ea47c379c4e05fc7d1cd" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transcripciones" ADD CONSTRAINT "FK_903a2d51d69ebfec640df10ae34" FOREIGN KEY ("audio_id") REFERENCES "audios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "transcripciones" DROP CONSTRAINT "FK_903a2d51d69ebfec640df10ae34"`);
        await queryRunner.query(`ALTER TABLE "claves_analisis" DROP CONSTRAINT "FK_07075d2ea47c379c4e05fc7d1cd"`);
        await queryRunner.query(`ALTER TABLE "data_analisis" DROP CONSTRAINT "FK_a976cce689ecc207b90becefff7"`);
        await queryRunner.query(`ALTER TABLE "data_analisis" DROP CONSTRAINT "FK_5ffef841f8f03bd6888d9404467"`);
        await queryRunner.query(`ALTER TABLE "parametros_analisis" DROP CONSTRAINT "FK_02ed9f13fac5b9029187a67c015"`);
        await queryRunner.query(`ALTER TABLE "parametros_analisis" DROP CONSTRAINT "FK_f3201dc908e496bd5bd7c02c154"`);
        await queryRunner.query(`ALTER TABLE "analisis" DROP CONSTRAINT "FK_65916bf2e092b02f14028789474"`);
        await queryRunner.query(`ALTER TABLE "analisis" DROP CONSTRAINT "FK_d1613a202455c30088f2e46f67d"`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP CONSTRAINT "FK_2222734377bc9808ae98cf12ff1"`);
        await queryRunner.query(`ALTER TABLE "tipo_analisis" DROP CONSTRAINT "FK_027ab74c366428aabca2307d9b8"`);
        await queryRunner.query(`ALTER TABLE "prompts" DROP CONSTRAINT "FK_086a37b64e93ca33df8effdf110"`);
        await queryRunner.query(`ALTER TABLE "data_audios" DROP CONSTRAINT "FK_3602b8cef079c15e5a6904bd845"`);
        await queryRunner.query(`ALTER TABLE "audios" DROP CONSTRAINT "FK_215af9f45b18ca75e45bf8eb0f1"`);
        await queryRunner.query(`DROP INDEX "REL_903a2d51d69ebfec640df10ae3" ON "transcripciones"`);
        await queryRunner.query(`DROP INDEX "IDX_4782c64a9308ca8fba2e787f9a" ON "transcripciones"`);
        await queryRunner.query(`DROP INDEX "IDX_e56c9150db8fb032219ce40ac5" ON "audios"`);
        await queryRunner.query(`ALTER TABLE "transcripciones" ALTER COLUMN "audio_id" int NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transcripciones" DROP COLUMN "transcripcion"`);
        await queryRunner.query(`ALTER TABLE "transcripciones" ADD "transcripcion" text`);
        await queryRunner.query(`ALTER TABLE "transcripciones" ADD CONSTRAINT "FK_903a2d51d69ebfec640df10ae34" FOREIGN KEY ("audio_id") REFERENCES "audios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "claves_analisis" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "claves_analisis" ADD "descripcion" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "claves_analisis" ADD CONSTRAINT "UQ_2664718930326ce317d19ce0776" UNIQUE ("clave")`);
        await queryRunner.query(`ALTER TABLE "data_analisis" ALTER COLUMN "clave_id" int NOT NULL`);
        await queryRunner.query(`ALTER TABLE "data_analisis" ALTER COLUMN "analisis_id" int NOT NULL`);
        await queryRunner.query(`ALTER TABLE "data_analisis" ADD CONSTRAINT "FK_a976cce689ecc207b90becefff7" FOREIGN KEY ("clave_id") REFERENCES "claves_analisis"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_analisis" ADD CONSTRAINT "FK_5ffef841f8f03bd6888d9404467" FOREIGN KEY ("analisis_id") REFERENCES "analisis"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parametros_analisis" ALTER COLUMN "tipo_analisis_id" int NOT NULL`);
        await queryRunner.query(`ALTER TABLE "parametros_analisis" ALTER COLUMN "prompt_id" int NOT NULL`);
        await queryRunner.query(`ALTER TABLE "parametros_analisis" ALTER COLUMN "name" varchar(255)`);
        await queryRunner.query(`ALTER TABLE "parametros_analisis" ADD CONSTRAINT "FK_02ed9f13fac5b9029187a67c015" FOREIGN KEY ("tipo_analisis_id") REFERENCES "tipo_analisis"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parametros_analisis" ADD CONSTRAINT "FK_f3201dc908e496bd5bd7c02c154" FOREIGN KEY ("prompt_id") REFERENCES "prompts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "analisis" ALTER COLUMN "parametro_id" int NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analisis" ALTER COLUMN "transcripcion_id" int NOT NULL`);
        await queryRunner.query(`ALTER TABLE "analisis" ADD CONSTRAINT "FK_65916bf2e092b02f14028789474" FOREIGN KEY ("parametro_id") REFERENCES "parametros_analisis"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "analisis" ADD CONSTRAINT "FK_d1613a202455c30088f2e46f67d" FOREIGN KEY ("transcripcion_id") REFERENCES "transcripciones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "claves_audios" ALTER COLUMN "descripcion" nvarchar(255)`);
        await queryRunner.query(`ALTER TABLE "claves_audios" ALTER COLUMN "clave" nvarchar(255)`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "cliente_id" int NOT NULL`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP CONSTRAINT "UQ_7b530f4aec186b2f02dd7ec9d41"`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD CONSTRAINT "FK_2222734377bc9808ae98cf12ff1" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clientes" DROP CONSTRAINT "UQ_0c14604e1a6e1b00fd341b1b2c0"`);
        await queryRunner.query(`ALTER TABLE "tipo_analisis" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "tipo_analisis" ADD "description" varchar(MAX)`);
        await queryRunner.query(`ALTER TABLE "prompts" ALTER COLUMN "template" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "data_audios" ALTER COLUMN "audio_id" int NOT NULL`);
        await queryRunner.query(`ALTER TABLE "data_audios" ALTER COLUMN "valor" nvarchar(255)`);
        await queryRunner.query(`ALTER TABLE "data_audios" ADD CONSTRAINT "FK_3602b8cef079c15e5a6904bd845" FOREIGN KEY ("audio_id") REFERENCES "audios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audios" ALTER COLUMN "servicio_id" int NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audios" ADD CONSTRAINT "DF_2d75961dcfd770605ff40f6545d" DEFAULT 0 FOR "transcrito"`);
        await queryRunner.query(`ALTER TABLE "audios" ALTER COLUMN "transcrito" int NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audios" ADD CONSTRAINT "FK_215af9f45b18ca75e45bf8eb0f1" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "claves_analisis" DROP COLUMN "servicio_id"`);
        await queryRunner.query(`ALTER TABLE "tipo_analisis" DROP COLUMN "servicio_id"`);
        await queryRunner.query(`ALTER TABLE "prompts" DROP COLUMN "servicio_id"`);
        await queryRunner.query(`ALTER TABLE "claves_analisis" ADD "servicioId" int NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_PARAMETROS_ANALISIS_COMPOSITE" ON "parametros_analisis" ("prompt_id", "tipo_analisis_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ANALISIS_COMPOSITE" ON "analisis" ("parametro_id", "transcripcion_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_SERVICIOS_NAME" ON "servicios" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_CLIENTES_NAME" ON "clientes" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_DATA_AUDIOS_COMPOSITE" ON "data_audios" ("audio_id", "clave_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_AUDIOS_TRANSCRITO" ON "audios" ("transcrito") `);
        await queryRunner.query(`ALTER TABLE "claves_analisis" ADD CONSTRAINT "FK_claves_analisis_servicio" FOREIGN KEY ("servicioId") REFERENCES "servicios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
